version: '3.8'

services:
  bazel:
    container_name: 'calendar-bazel'
    image: insready/bazel:latest
    tty: true
    volumes:
      - type: bind
        source: .
        target: /usr/src/
        read_only: false
    networks:
      - calendar-bazel-network

networks:
  calendar-bazel-network:
    driver: bridge
