version: '3.8'

services:
  bazel:
    container_name: 'calendar-bazel'
    image: l.gcr.io/google/bazel:latest 
    tty: true
    working_dir: /var/www/
    volumes:
      - type: bind
        source: .
        target: /var/www/
        read_only: false
    ports:
      - 8080:3000
    expose:
      - 3000
    entrypoint: ["bazel", "run", ":serve"]
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge
